### ISSUE TITLE
Ability to reference page items in Details Query

### ISSUE THREAD

**Issue by zhudock** [Pretius/apex-nested-reports#1]
I'd like to suggest the ability to reference a page item in addition to a clicked column value as part of the details query.

For example:
`SELECT * FROM emp WHERE dept = #DEPT# AND user_id = :P10_USER_ID`

**Comment by waynelen6** [comment]
Hai, I having error  ORA-00911: invalid character in details query while using hash.
am I missout something?

**Comment by bostrowski** [comment]
@zhudock Refrencing items value from session should be working. I assume you want to get current value from GUI not from the session?

**Comment by bostrowski** [comment]
@waynelen6 please reproduce your use case on apex.oracle.com and post WS name / login credentials in new issue. This thread is about referencing APEX page items.

**Comment by zhudock** [comment]
@bostrowski I must have had some other issue on my page. After trying again today, I can confirm all is working as expected.

Correction...

Using V('ITEM_NAME') works to access the page item, but :ITEM_NAME does not.

However, I'd consider this a valid workaround, and suggest adding that note to the documentation

**Comment by zhudock** [comment]
Correction...

Using V('ITEM_NAME') works to access the page item, but :ITEM_NAME does not.

However, I'd consider this a valid workaround, and suggest adding that note to the documentation

**Comment by sokosp** [comment]
Hi, great work, but i have some problem as waynelen6.

ORA-00911: invalid character in details query while using hash

**Comment by bostrowski** [comment]
@sokosp:

Switch your application builder to "Page designer" mode. In "Component view" SQL queries are parsed before saving.

@zhudock: 

In next version the plugin will send item value from gui to session each time plugin is triggered.

**Comment by sokosp** [comment]
thanks @bostrowski . I ll try now..
It saved that way, but now i get:
Error occurred while painting error page: ORA-01403: no data found ORA-01403: no data found

below the query in the dynamic action on the nested report.
It doesn't understand the # ..... I think

select e.DESCRPTION Surcharge_Details,
       DECODE(a.amnt,NULL,null,TO_CHAR(a.amnt,'999G990D90')||' '||b.code) Amount
from RESULTS_PRICES_DETAILS a,currency b,AGENT_DEBITS e
where a.RESULATSID = #RESULATSID#
  and a.DEBITID = e.DEBITID
  and b.currencyid = a.currencyid

When i choose MODE: CUSTOM TEMPLATE & CUSTOM CALLBACK it asks values for Custom Template and Custom Callback. What do we enter in the so it shows same as your demo?

**Comment by bostrowski** [comment]
@sokosp 
You mean displaying details query in boostrap popover?

**Comment by sokosp** [comment]
@bostrowski  yes.
But also i can't getting to work, as you can see (i edited my message)

**Comment by bostrowski** [comment]
@sokosp 
You are getting this error while loading page? If yes, it is not the plugin problem. If not, reproduce your issue on apex.oracle.com and send me login credentials to bostrowski@pretius.com.

**edit:**
regarding your question about custom template & custom callback from demo example: I'm writing blog post about it, so you have to wait. Follow me on twitter (@bostrowsk1) to be up to date.

**Comment by waynelen6** [comment]
Thanks @bostrowski , after I switch to application builder to "Page designer" mode, it fixed the error.
And its working now, but for the first few rows trigger error as below link. The rest are working perfectly.

https://www.dropbox.com/s/fglxafpdtb35gxr/Untitled.png?dl=0

**Comment by bostrowski** [comment]
@waynelen6 
after getting this alert inspect Console > Network tab. In ajax response is JSON text object that wasn't parsed successfully because of syntax error. You might need to inspect data that is returned. In fetched row might be white space that breaks JSON syntax.

**Comment by waynelen6** [comment]
Thanks @bostrowski I found the problem already.
In details query #COLUMN_NAME# which have value start with '0' cause the error.

**Comment by bostrowski** [comment]
@sokosp
Implementing bootstrap as custom callback: http://pretius.com/pretius-apex-nested-reports-plugin-with-bootstrap-popover/

**Comment by hairpin86** [comment]
Hi,

Thanks for the great plugin. Unfortunately I am also getting the ORA-00911: invalid character error when using a bind variable like #ID#.

I tried Page Designer as well as Component View, both did not work.

Is there a workaround?

Thanks and best regards

**Comment by hairpin86** [comment]
Hi,

Column was Hidden.
Solved as it was described in the Plugin Help:

 Referencing not visible columns

When column in report has "Type" = "Hidden" it is not rendered in report and can't be referenced by the plugin. To reference such column, its value has to be provided within visible column.

In Classic report are defined columns

```
column CUSTOMER_ID, Type = "Hidden"
column CUSTOMER, Type = "Plain Text"
```

Column CUSTOMER is visible and can contain CUSTOMER_ID value. To do so go to section Column Formatting > HTML Expression and enter HTML:

<span class="CUSTOMER_ID" style="display:none">#CUSTOMER_ID#</span>#CUSTOMER#  

Thanks! Great PLUGIN!

**Comment by luistorrescas** [comment]
hi, how Create new derived column and set “Type” to “Plain text”

**Comment by bostrowski** [comment]
@luistorrescas 
I assume you want unescaped HTML in report? This feature will be fully supported in next release.

**Comment by bostrowski** [comment]
APEX items are supported since version 2. Closed.

**Comment by Dulal66** [comment]
Hi Bostrowski,
I am trying your apex nested reports (drilldown) plugin with bootstrap popover with Oracle Apex 19.1
but it is giving error. Would you kindly help me with the step by step implement working process.
