### ISSUE TITLE
Not compatible with the Apex 18

### ISSUE THREAD

**Issue by gecsafunk** [Pretius/apex-nested-reports#10]
Do you have a plan to upgrade this great plugin for the Apex 18 version?
This plugin probably not compatible with the 18 version default Universal Theme ..if I use with the upgraded application it is working, but if i create a brand new app, then I get these errors:

ReferenceError: reference to undefined property "velocity"  desktop_all.min.js:41:3399
ReferenceError: reference to undefined property "stopped"  desktop_all.min.js:41:18541
ReferenceError: reference to undefined property "result"  desktop_all.min.js:3:10455
ReferenceError: reference to undefined property "disabled"  desktop_all.min.js:3:10623
ReferenceError: reference to undefined property "uniqueID"  desktop_all.min.js:2:19880
ReferenceError: assignment to undeclared variable nestedHeaderTag  pretius_nestedreport.js:203:25
ReferenceError: reference to undefined property "getValue"  desktop_all.min.js:18:2540
TypeError: headerTag.size is not a function  pretius_nestedreport.js:206:12

Thanks,
Geza

**Comment by allipierre** [comment]
Issue was: size() was removed in version 3 of jQuery, use length instead.
you can download the Demo(f30153_pretius) and the modified plugin on Github
https://github.com/allipierre/Simple-IG

Demo

https://apex.oracle.com/pls/apex/f?p=30153:52

**Comment by swesley** [comment]
I concur - I changed references in two supporting .js files from .size() to .length, and the plugin behaves ok.

**Comment by bostrowski** [comment]
included in v2.0.2. Thanks!
