### ISSUE TITLE
No Data Found message doesn't translate

### ISSUE THREAD

**Issue by EwenDC** [Pretius/apex-nested-reports#11]
Hi, The company I work for is making an application for a business that uses the nested reports plugin extensively. The application needs to be in English and French as per the businesses requirements. When we did a XLIFF export for translation the No Data Found message wasn't included. No big deal, the message was in the translation repository so we just translated it there.

The issue is that even though the message has a translation in the repository, no matter how many times we seed and publish the application the No Data Found message is still in English.
![Translation Repository](https://preview.ibb.co/eQ48yT/Repository.png)
![Nested Report](https://preview.ibb.co/b60gJT/Report.png)

Unfortunately I can't wait for this to be fixed so I'm going to have to find a workaround or edit the plugin to fix this. If I do the latter I'll post what I did here.

**Comment by bostrowski** [comment]
@EwenDC 
It's been long time, but I will be updating the plugin and I will make this message translatable. Thanks!
