### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by santhoshkillari** [Pretius/apex-nested-reports#12]
Hello,

Nice plugin, I would like to use this plugin for my application. But

I have successfully configured and while clicking the search icon, console error is appearing, please find the below screenshot for your reference.
![image](https://user-images.githubusercontent.com/34837897/43673396-3f0c555c-97e0-11e8-8184-1999f0b6207f.png)

Is there any apex version limitation? or did i miss anything to set?

Is it possible to use graphs instead of nested report.??

Please help me.

Thank you.
Santosh

**Comment by bostrowski** [comment]
@santhoshkillari 
it looks like you are trying to use the plugin with APEX 18.1 which is not yet supported. Contact me via e-mail bostrowski@pretius.com regarding apex version.

> Is it possible to use graphs instead of nested report.??

Yes but with custom callback (apex attribute) where you have to provide your JS which will render the graph.

**Comment by allipierre** [comment]
Issue was: size() was removed in version 3 of jQuery, use length instead.
you can download the Demo(f30153_pretius) and the modified plugin on Github
https://github.com/allipierre/Simple-IG

Demo

https://apex.oracle.com/pls/apex/f?p=30153:52

**Comment by santhoshkillari** [comment]
Thank you Alli. Now Its working fine without any issue.

**Comment by bostrowski** [comment]
included in v2.0.2. Thanks!
