### ISSUE TITLE
pretiusNestedReport is undefined

### ISSUE THREAD

**Issue by davesheffield** [Pretius/apex-nested-reports#17]
Hello,

my APEX Version is 18.1 and I use IE 11
I've installed the plugin as described.
But on the page where the plugin is used, I get the following scripterror by clicking on the column link.

SCRIPT5009: "pretiusNestedReport" ist undefiniert

{"triggeringElementType":"JQUERY_SELECTOR","triggeringElement":".showDetailsAuftraege","bindType":"live","bindDelegateTo":"body","bindEventType":"click","anyActionsFireOnInit":false,actionList:[{"eventResult":true,"executeOnPageInit":false,"stopExecutionOnError":true,"affectedElementsType":"REGION","affectedRegionId":"R13872964593976501",javascriptFunction:
    function(){
      pretiusNestedReport(this, {
"queryColumns":[
"DETAILSVIEW"
]
}
, {

I have no Idea what is wrong. It seems to me that apex does not know or does not find the plugin.
Can it be related to a wrong #PLUGIN_FILES# or #IMAGE_PREFIX#?

**Comment by bostrowski** [comment]
@davesheffield 

The plugin in version you have installed wasn't compatibile with APEX 18+. Please try new release v2.0.2 and let me know if your issue is still up to date.
