### ISSUE TITLE
install new package

### ISSUE THREAD

**Issue by zhudock** [Pretius/apex-nested-reports#18]
The Readme indicates to install the new pl/sql package in the Oracle APEX schema. Can you clarify if that means the parsing schema for the application, or the Oracle-owned APEX schema, e.g. `APEX_180100`

**Comment by bostrowski** [comment]
@zhudock 
It's parsing schema for application so you can do it using SQL Workhop, I've updated readme file, thanks!

edit: do you need any further assistance or can I close the issue? I will be waiting for your answer till end of week, then I will close the issue.

**Comment by zhudock** [comment]
Excellent. Thank you for the explanation
