### ISSUE TITLE
Column format

### ISSUE THREAD

**Issue by mathiasmaciel97** [Pretius/apex-nested-reports#20]
How can I format columns in reports?
In this case I tried to format the columns named **Fecha Salida** and **Fecha Entrada** to this date format _DD-MM-RR_, but it doesn't work.
Another questions is... how can I set heading and column alignment? As I see it comes left alignment by default.
Is there a way to do them?

![01](https://user-images.githubusercontent.com/39440207/61558112-2195d680-aa34-11e9-8b3a-51c4a3775241.png)

**Comment by bostrowski** [comment]
@mathiasmaciel97 

> How can I format columns in reports?
> In this case I tried to format the columns named Fecha Salida and Fecha Entrada to this date format DD-MM-RR, but it doesn't work.

just use to_char function in your SQL statement. But don't forget about alias which will be used as heading.

> Another questions is... how can I set heading and column alignment? As I see it comes left alignment by default.
> Is there a way to do them?

yes, you have to write a little of CSS that will set aligment of cell and header for nested report table. For example (from live demo app) you can write CSS rule that wil align cells content

```CSS
td[headers="NR_1_ENAME"] {
  text-align: right;
}
```

![image](https://user-images.githubusercontent.com/15342508/61812192-509cb580-ae43-11e9-849b-08ef5f18f5bd.png)

using this technique you can align headers etc.

**Comment by bostrowski** [comment]
@mathiasmaciel97 
Do you have any other questions? if not I'll close the issue.

**Comment by mathiasmaciel97** [comment]
Thanks!
Don’t worry I’ll do it for you!
