### ISSUE TITLE
Plugin Ajax Error. Error en el código PLSQL provocado durante el procesamiento del plugin

### ISSUE THREAD

**Issue by gallis1** [Pretius/apex-nested-reports#21]
Hi. I've installed the plugin on APEX 19.1
I've followed the steps to create a report, but pass an error
![image](https://user-images.githubusercontent.com/9946516/71408532-e29d2a00-263e-11ea-84b1-ed5b60af1849.png)
I need help.

**Comment by bostrowski** [comment]
@gallis1 
please recreacte your issue at apex.oracle.com on emp/dept table and send me developer credentials so I can check it (ostrowski.bartosz@gmail.com).

**Comment by gallis1** [comment]
Hi. I have already made it work.
The problem was that the SQL statement of the dynamic action, I ended it with a semicolon.
Thanks.
