### ISSUE TITLE
hybrid callback

### ISSUE THREAD

**Issue by Taha19861986** [Pretius/apex-nested-reports#24]
Dear all,
 i'am using default callback but in the same time i want to execute a js function after the sub-report is already loaded. any help.

**Comment by bostrowski** [comment]
Use the default callback event that is exposed by the plugin.

**Comment by Taha19861986** [comment]
how i can use it. when i select default callback the "Custom callback" prop is hidden. so, where i have to write my code

**Comment by bostrowski** [comment]
Its the plugin **event** not the plugin attribute. you need dynamic action that will be listening to the plugin event which is available via dynamic action attribute **When \ Event**.

Description of the plugin event is available here on GitHub: https://github.com/Pretius/apex-nested-reports#plugin-events

**Comment by Taha19861986** [comment]
i'am so sorry, but it is not clear for me. do you have any demo or screenshot of this solution.

**Comment by bostrowski** [comment]
It is as simple as possible.:

![image](https://user-images.githubusercontent.com/15342508/75684222-a28aa100-5c98-11ea-8268-9ceccd82dd14.png)

Embed your JavaScript code in **Execute JavaScript Code** true action.

**Comment by Taha19861986** [comment]
thanks alot

**Comment by bostrowski** [comment]
@Taha19861986 
Can we close the issue?
