### ISSUE TITLE
ORA-01403: no data found

### ISSUE THREAD

**Issue by TodGoulds** [Pretius/apex-nested-reports#25]
I am seeing a ORA-01403: no data found error when i am saving the dynamic action... the main query uses this query:

select * from (
select REGION, QTR, SALES_CREDIT
from ATTAINMENT)
pivot (SUM(SALES_CREDIT) for QTR in (
'Q120' as Q1, 'Q220' as Q2, 'Q320' as Q3, 'Q420' as Q4))
order by 1, 2

the dynamic action uses:

Select * from (
select DIRECTOR, QTR, SALES_CREDIT
from ATTAINMENT)
pivot (SUM(SALES_CREDIT) for QTR in (
'Q120' as Q1, 'Q220' as Q2, 'Q320' as Q3, 'Q420' as Q4))
where REGION = #REGION#
order by 1, 2

when i try and save teh report it fails, and will not allow me to save, just showing the abvoe error....????

**Comment by bostrowski** [comment]
@TodGoulds 
Start with fixing the query from
```sql
(...)
where REGION = #REGION#
(...)
```
to
```sql
(...)
where REGION = '#REGION#'
(...)
```

Column markers have to be enclosed with the apostrophe.

Ps.
be sure to use latest version of the plugin.

**Comment by TodGoulds** [comment]
thank you !

**Comment by bostrowski** [comment]
@TodGoulds 
Is it all? can we close the issue? :-)
