### ISSUE TITLE
Unescaped HTML for custom template

### ISSUE THREAD

**Issue by xcervicek** [Pretius/apex-nested-reports#28]
My SQL returns already a HTML formated code which now works fine with default template, but I need to use it with a custom template. 
Is it possible somehow ?
Btw, thank you for the super-trooper strong plugin !

**Comment by bostrowski** [comment]
@xcervicek 
Sure you can.

Use `{{{COLUMN_NAME}}}` instead of `{{COLUMN_NAME}}`. Triple brackets don't escape HTML tags.

**Comment by xcervicek** [comment]
Works perfectly fine ! Thanks
