### ISSUE TITLE
Default Template - Dont Escape HTML

### ISSUE THREAD

**Issue by GrazzMan** [Pretius/apex-nested-reports#3]
Would be nice if their was a way to tell it to not Escape Special Characters. Once detail report is open, trying to use the apex_util.prepare_url  to then do Modal windows.

**Comment by bostrowski** [comment]
@GrazzMan please provide example of details query and I will investigate it.

**Comment by GrazzMan** [comment]
Select '<a onclick="void(0)">click me</a>' from dual

It is escaping html and printing it instead of making the hyperlink. Any html in any detail query.

**Comment by bostrowski** [comment]
The plugin is using [WRITE Procedure Signature 7](https://docs.oracle.com/cd/E59726_01/doc.50/e39149/apex_json.htm#AEAPI29817). The procedure does not support parameter preventing HTML from escaping.

I need to rethink this, but yes, the fetature should be implemented in next version of the plugin. 
Thank you for your contribution.

**Comment by GrazzMan** [comment]
In the mean time, is their a spot in the code after the WRITE procedure where I could put a Replace string?? I can manipulate the query to send a code that I can replace with the html I need. Just dont know a good spot to do this (dont do json stuff).

**Comment by hairpin86** [comment]
Hi,

Is there any solution yet to not escpae html. It would be perfect to use links or different styling within the supreport.

Thanks

**Comment by bostrowski** [comment]
Unescaped HTML is supported since version 2. Closed.
