### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by herz08** [Pretius/apex-nested-reports#31]
Hi Bartosz,
The help texts are very extensive and very good, but the plugin has so many possibilities, which you also show in your demo application and it is sometimes difficult for me to bring the complex things together. I would love it if you could make your demo application available for download. If that is possible, I would be very happy. 

Best regards 
Oliver

**Comment by bostrowski** [comment]
@herz08 
Hi, I'm no longer part of Pretius team hence please contact with Przemysław Staniszewski pstaniszewski@pretius.com. As far as I know he already sent you a message at LN.

**Comment by herz08** [comment]
Hi Bartosz,

thank you for the fast answer. Sorry I should know this better, of course you are now a team member of United Code. I have still R & D in my mind. But you’re still the Face in the Demo App, so I don‘t think about it.

Best Regards 
Oliver
