### ISSUE TITLE
Is the plugin work on Oracle APEX Version 20.1.0.00.13

### ISSUE THREAD

**Issue by sujan-paidipala** [Pretius/apex-nested-reports#33]
I followed the instruction, but when i click on the link, page is failing.

Addrs Bar URL changes to below value : 
https://apex.internal.com/pls/apex/%3Cspan%20class=%22fa%20fa-search%22%3E%3C/span%3E%3Cspan%20class=%22NAME%22%20style=%22display:%20none%22%3Etesting%3C/span%3E

And the browser page ridirects to 404 not found. with below error message
`The request could not be mapped to any database. Check the request URL is correct, and that URL to database mappings have been correctly configured`

**Comment by sujan-paidipala** [comment]
Below is the debug log


0.14611 | 0.00002 | Dynamic Action meta data: | 4 | 0%
-- | -- | -- | -- | --
0.14613 | 0.00002 | id: 13776609873103503323 | 4 | 0%
0.14616 | 0.00002 | action: PLUGIN_PRETIUS_APEX_NESTED_REPORTS | 4 | 0%
0.14617 | 0.00002 | attribute_01: select * from mt_vms where pod_name='#POD_NAME#'; | 4 | 0%
0.14619 | 0.00002 | attribute_02: CE:AA:CR | 4 | 0%
0.14620 | 0.00002 | attribute_03: DTDC | 4 | 0%
0.14622 | 0.00002 | attribute_04: | 4 | 0%
0.14623 | 0.00002 | attribute_05: | 4 | 0%
0.14625 | 0.00002 | attribute_06: #EBEBEB | 4 | 0%
0.14626 | 0.00002 | attribute_07: | 4 | 0%
0.14628 | 0.00002 | attribute_08: #c5c5c5 | 4 | 0%
0.14629 | 0.00002 | attribute_09: #e3e3e3 | 4 | 0%
0.14631 | 0.00002 | attribute_10: | 4 | 0%
0.14633 | 0.00002 | attribute_11: No data found | 4 | 0%
0.14634 | 0.00001 | attribute_12: | 4 | 0%
0.14636 | 0.00001 | attribute_13: | 4 | 0%
0.14637 | 0.00001 | attribute_14: | 4 | 0%
0.14639 | 0.00002 | attribute_15: | 4 | 0%
0.14640 | 0.00002 | init_javascript_code: | 4 | 0%
0.14642 | 0.00002 | triggering_region_id: | 4 | 0%
0.14643 | 0.00002 | affected_elements_type: REGION | 4 | 0%
0.14645 | 0.00002 | affected_region_id: 1463127005944291246 | 4 | 0%
0.14646 | 0.00001 | affected_button_id:

**Comment by sujan-paidipala** [comment]
looks like, this is failing because, i had URL with < span > tags, this is being replaced in the URL and failing.
When i changed the URL content to  f?p=&APP_ID.:&PAGEID:&APP_SESSION.
I dont see error any more, but the nested report collapses, without showing the content
Is this a known issue ?
Right now, i dont see 404 error page anymore, but the nested report collapses in fraction of seconds.

**Comment by sujan-paidipala** [comment]
I ended up here.
Because of the link text on the column, once the nested region expands... link page is reloading and expanded region is collapsing again

**Comment by sujan-paidipala** [comment]
if i takeout "click" dynamic action and add "mouse enter" it works good.

**Comment by sujan-paidipala** [comment]
link text has been replaced with # then issue resolved.!

**Comment by KamilKosiorek** [comment]
You can also use the URL: "javascript: void (0);"

**Comment by bostrowski** [comment]
@sujan-paidipala 

- href attribute accepts only valid web protocols, relative URLs, inline javascript code, and anchors ("#"). Using the character "#" is invalid in your approach.

Use ```javascript:void(0);``` just like @kkosiorek94 mentioned.

Yes, the plug-in does work with APEX 20.1.

Ps.
> I followed the instruction, but when i click on the link, page is failing.

I'm not sure about it - "href" value ;-)

I'm glad you have managed to make the plug-in work for you.
