### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by velocity1234** [Pretius/apex-nested-reports#37]
I followed exact steps and am getting the error when click on the derived column link.

404 Not Found
2021-07-12T17:28:01.429Z | 005lj1lSzLoFw0KimTtlWJ0003Yq0000hR
![image](https://user-images.githubusercontent.com/51320375/125330839-dd104d80-e364-11eb-9d55-aa229c383817.png)

The request could not be mapped to any database. Check the request URL is correct, and that URL to database mappings have been correctly configured

**Comment by bostrowski** [comment]
Hi @velocity1234 

You are right, the usage guide was malformed. I've updated usage guide, please give it a try one more time :-)

changes:
![image](https://user-images.githubusercontent.com/15342508/125409725-7a4aa080-e3bc-11eb-8e05-e9e0048a02d1.png)

fixed usage guide:
![image](https://user-images.githubusercontent.com/15342508/125409819-95b5ab80-e3bc-11eb-93d5-35fd5d983e37.png)

**Comment by velocity1234** [comment]
It is working fine now. Thanks for the prompt response!
