### ISSUE TITLE
Performance concern

### ISSUE THREAD

**Issue by swesley** [Pretius/apex-nested-reports#5]
The substituted value is not using bind variable, a literal value is used instead
https://community.oracle.com/message/14213744

Can you think of SQL solution or does the row details function need refactoring?

**Comment by rimblas** [comment]
I agree with Scott.

I would like to suggest that the SQL for the nested tables should use bind variables. There is a security aspect to using bind variables, which I think the plugin tries to mitigate. But even more critical is the performance aspect. Binds allow the Oracle DB to re-use SQL statements. Currently, every child query becomes a unique SQL and this is costly.

This is a good plugin, but if it used bind variables for the nested table query it would be great!

I may be able to look into it and provide a pull request. I just don't want to double up efforts if you're already working on it.

Here's a small video/blog I did on the importance of bind variables:
http://rimblas.com/blog/2016/09/video-006-substitution-strings-bind-variables-and-apex-links/

**Comment by rimblas** [comment]
@swesley v2 addresses this issue and I believe it can now be closed.

**Comment by bostrowski** [comment]
As @rimblas said. It's fixed since version 2. Closed.
