### ISSUE TITLE
Interactive Grid

### ISSUE THREAD

**Issue by semiautomatix** [Pretius/apex-nested-reports#8]
This plugin "almost" works with the interactive grid. Unfortunately adding new rows, or updating the model seems to prevent the nested report from showing. Any ideas?

**Comment by bostrowski** [comment]
@semiautomatix 
The plugin is not designed for interactive grid. But yes, its working with IG with some CSS issues. But they are not related to your question. Keep in mind that the plugin is dedicated to Classic/Interactive reports.

Regarding your question. Have you used **dynamic** Scope for dynamic action? It sounds like you have left **Scope** with default value **Static**.

**Comment by semiautomatix** [comment]
Thanks, looks like it's something to do with the grid changing in edit mode. I've overcome most issues, but not all.

**Comment by semiautomatix** [comment]
By the way, can we have a CR for interactive grids?

**Comment by bostrowski** [comment]
@semiautomatix 
I would love to extend the plugin to support IG but I can't say when it will be done. There are plenty of my plugins waiting to be rewritten and I'm developing plugins in my spare time as side work. In most cases plugin bugs are first to be done.

**Comment by vincentmorneau** [comment]
@bostrowski Any news on IG support?

**Comment by hairpin666** [comment]
Any development on IG support? Would like to use it on a read-only IG.

**Comment by bostrowski** [comment]
@hairpin666 
the plugin can be bound with any HTML table and you can do it right now. The only obstacle are frozen columns.

Regarding IG support. I will be working on it for future releases. It's part of roadmap.
